### ISSUE TITLE
error during the package installation

### ISSUE THREAD

**Issue by surendraphd** [schwallergroup/saturn#1]
Hi,

I encountered an error during the installation of the package using the setup.sh script, specifically with the causal-conv1d and mamba-ssm packages. Manual installation of these packages also results in the following error:

(saturn) user@user:~/Downloads/saturn$ pip install causal-conv1d>=1.2.0
Collecting mamba-ssm
  Using cached mamba_ssm-1.2.2.tar.gz (35 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-5cf7j5zt/mamba-ssm_32f156da05014f5ea350e15e9a64e1fe/setup.py", line 103, in <module>
          raise RuntimeError(
      RuntimeError: mamba_ssm is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.
      
      torch.__version__  = 1.12.1+cu113
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(saturn) user@user:~/Downloads/saturn$ pip install mamba-ssm
Collecting mamba-ssm
  Using cached mamba_ssm-1.2.2.tar.gz (35 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-iwpc6s9g/mamba-ssm_164c385c52324c8ebe2ef8f9265db92e/setup.py", line 103, in <module>
          raise RuntimeError(
      RuntimeError: mamba_ssm is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.
      
      
      torch.__version__  = 1.12.1+cu113
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I have also tried verifying my PyTorch version and CUDA compatibility, which appear to be correct:

Python 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(f"PyTorch version: {torch.__version__}")
PyTorch version: 1.12.1+cu113
>>> exit()

Could you please provide guidance on how to successfully install these packages?

Thanks

**Comment by GuoJeff** [comment]
Hi @surendraphd,

Sorry for the error. I have pushed a change to `setup.py`. Would you be able to try re-installing?

**Comment by surendraphd** [comment]
Hi GuoJeff,
Thank you for your quick response. Unfortunately, the changes did not resolve the issue.
I am sharing the terminal log in the attached *.txt file for further review.

Thanks,

[saturn_installation_error.txt](https://github.com/schwallergroup/saturn/files/15477107/saturn_installation_error.txt)

**Comment by GuoJeff** [comment]
Hi @surendraphd,

Could you share your system configuration? I just re-tested installing the environment on 2 systems (with NVIDIA RTX 3090 and RTX A6000). 

From the error in the text file: `ImportError: cannot import name 'packaging' from 'pkg_resources'`, could you try `pip install setuptools` before installing the `causal-conv1d` and `mamba-ssm` packages?

**Comment by surendraphd** [comment]
Hi GuoJeff,

Thank you for your response.
Here is my system details.
I am using Ubuntu 20.04 with NVIDIA GeForce RTX 3070.

(base) user@user:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

(base) user@user:~$ lscpu
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      46 bits physical, 48 bits virtual
CPU(s):                             36
On-line CPU(s) list:                0-35
Thread(s) per core:                 2
Core(s) per socket:                 18
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              85
Model name:                         Intel(R) Xeon(R) W-2295 CPU @ 3.00GHz
Stepping:                           7
CPU MHz:                            3000.000
CPU max MHz:                        4800.0000
CPU min MHz:                        1200.0000
BogoMIPS:                           6000.00
Virtualization:                     VT-x
L1d cache:                          576 KiB
L1i cache:                          576 KiB
L2 cache:                           18 MiB
L3 cache:                           24.8 MiB
NUMA node0 CPU(s):                  0-35

**Comment by GuoJeff** [comment]
Hi @surendraphd,

I checked the Ubuntu system (on the 2 machines I have access to) and they have the same version as yours. I was able to install the environment with the latest changes which enforced the `causal-conv1d` and `mamba-ssm` versions. 

Would you be able to try `pip install setuptools` and then manually try the pip commands for `causal-conv1d` and `mamba-ssm` again?

**Comment by surendraphd** [comment]
Hi GuaJeff,

Thank you for your support.

Although none of the suggested solutions worked for me initially, I managed to install the package successfully. If others face similar issues, they might find the following approach helpful:

1. Install all required packages except PyTorch with CUDA 11.3, causal-conv1d, and mamba-ssm.

2. After completing the initial installations, proceed with the following commands:

pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu118

wget https://github.com/Dao-AILab/causal-conv1d/releases/download/v1.1.3.post1/causal_conv1d-1.1.3.post1+cu118torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl

wget https://github.com/state-spaces/mamba/releases/download/v1.1.1/mamba_ssm-1.1.1+cu118torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl

pip install causal_conv1d-1.1.3.post1+cu118torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl 

pip install mamba_ssm-1.1.1+cu118torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl

This method worked for me, allowing me to successfully run config.json located in the part-1 folder.

**PS: Please note that my machine has CUDA 11.3 installed, and I believe PyTorch with CUDA 11.8 is also compatible with CUDA 11.3.**

Thanks,

**Comment by GuoJeff** [comment]
Hi @surendraphd,

Thank you for sharing your solution. I have updated the README to point to this issue in case others experience a similar problem.

Thank you also for trying out Saturn.
